# Generated by Django 3.1.7 on 2021-04-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearpaidamount',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
